# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c0c61a88e8ac463f70fe79f34ace9022db202a0ef1fad524461a14e281d8e2ad00e08cc9d6d7a0289ff46ca804b4735e9a3a2d608a748361c04dbdaf7cacf98

test:
  secret_key_base: 04865c5d1916e1a37e8dbea661a456639e1e5b306cc1350918b3058d73b781374c59515b24724084d19970c14cb9ee28b52588a20e3ae84d5f79af9924e3ac04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
